openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://load-balancer-timesheet-595005313.us-east-1.elb.amazonaws.com
    description: Generated server url
tags:
  - name: Usuários
    description: Controller que gerencia as ações possíveis de um usuário
  - name: Relatórios
    description: Controller que gerencia a emisão de relatório
  - name: Registro de Ponto
    description: Controller que gerencia as ações possíveis de um ponto de um funcionário
paths:
  /users/{userId}/change-password:
    put:
      tags:
        - Usuários
      summary: Atualizar senha
      description: Atualiza a senha de um usuário
      operationId: updatePassword
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordUpdRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
      x-amazon-apigateway-integration:
        httpMethod: "PUT"
        uri: "${url_timesheet_service}/users/{userId}/change-password"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.userId: "method.request.path.userId"
        passthroughBehavior: "when_no_match"
        type: "http"
  /users:
    post:
      tags:
        - Usuários
      summary: Criar usuário
      description: Cria um usuário para o funcionário
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/users"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        type: "http"

  /users/{userId}/activation:
    post:
      tags:
        - Usuários
      summary: Ativar ou desativar usuário
      description: Deixa o usuario como ativo ou inativo um usuário
      operationId: activateOrDeactivate
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserActivationRequest'
        required: true
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/users/{userId}/activation"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.userId: "method.request.path.userId"
        passthroughBehavior: "when_no_match"
        type: "http"

  /reports/generate/{employeeId}/dot-mirror:
    post:
      tags:
        - Relatórios
      summary: Gerar relatório espelho de ponto
      description: Gera o relatório espelho de ponto de um funcionário
      operationId: generateDotMirrorReport
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/reports/generate/{employeeId}/dot-mirror"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
        passthroughBehavior: "when_no_match"
        type: "http"

  /reports/generate/{employeeId}/dot-mirror/{year}/{month}:
    post:
      tags:
        - Relatórios
      summary: Gerar relatório espelho de ponto para um mês e ano especifico
      description: Gera o relatório espelho de ponto de um mês e ano especifico de um funcionário
      operationId: generateDotMirrorReport_1
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: year
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: month
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/reports/generate/{employeeId}/dot-mirror/{year}/{month}"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
          integration.request.path.year: "method.request.path.year"
          integration.request.path.month: "method.request.path.month"
        passthroughBehavior: "when_no_match"
        type: "http"


components:
  schemas:
    PasswordUpdRequest:
      required:
        - password
      type: object
      properties:
        password:
          type: string
    UserResponse:
      type: object
      properties:
        userId:
          type: string
        employeeId:
          type: integer
          format: int64
        active:
          type: boolean
    UserRequest:
      required:
        - employeeId
        - password
        - userId
      type: object
      properties:
        userId:
          type: string
        password:
          type: string
        employeeId:
          type: integer
          format: int64
    UserActivationRequest:
      required:
        - active
      type: object
      properties:
        active:
          type: boolean
    LocalTime:
      type: object
      properties:
        hour:
          type: integer
          format: int32
        minute:
          type: integer
          format: int32
        second:
          type: integer
          format: int32
        nano:
          type: integer
          format: int32
    PointRecordResponse:
      type: object
      properties:
        pointRecordId:
          type: integer
          format: int64
        employeeId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        time:
          $ref: '#/components/schemas/LocalTime'
        type:
          type: string
          enum:
            - IN
            - OUT
    PointRecordRequest:
      type: object
      properties:
        pointRecordId:
          type: integer
          format: int64
        employeeId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        time:
          $ref: '#/components/schemas/LocalTime'
        type:
          type: string
          enum:
            - IN
            - OUT
    DadosAutenticacao:
      type: object
      properties:
        login:
          type: string
        senha:
          type: string
    EmployeeRequest:
      required:
        - email
        - name
        - role
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - SELLER
            - BUYER
            - TECHNICIAN
    EmployeeResponse:
      type: object
      properties:
        employeeId:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - SELLER
            - BUYER
            - TECHNICIAN
        active:
          type: boolean
    PointRecordTotalResponse:
      type: object
      properties:
        pointRecordResponseList:
          type: array
          items:
            $ref: '#/components/schemas/PointRecordResponse'
        totalWorkedHours:
          $ref: '#/components/schemas/LocalTime'
    Empty:
      title: "Empty Schema"
      type: "object"
