openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://load-balancer-timesheet-595005313.us-east-1.elb.amazonaws.com
    description: Generated server url
tags:
  - name: Usuários
    description: Controller que gerencia as ações possíveis de um usuário
  - name: Relatórios
    description: Controller que gerencia a emisão de relatório
  - name: Registro de Ponto
    description: Controller que gerencia as ações possíveis de um ponto de um funcionário
paths:
  /users/{userId}/change-password:
    put:
      tags:
        - Usuários
      summary: Atualizar senha
      description: Atualiza a senha de um usuário
      operationId: updatePassword
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PasswordUpdRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
      x-amazon-apigateway-integration:
        httpMethod: "PUT"
        uri: "${url_timesheet_service}/users/{userId}/change-password"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.userId: "method.request.path.userId"
        passthroughBehavior: "when_no_match"
        type: "http"

  /users:
    post:
      tags:
        - Usuários
      summary: Criar usuário
      description: Cria um usuário para o funcionário
      operationId: create
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/users"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"
        type: "http"

  /users/{userId}/activation:
    post:
      tags:
        - Usuários
      summary: Ativar ou desativar usuário
      description: Deixa o usuario como ativo ou inativo um usuário
      operationId: activateOrDeactivate
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserActivationRequest'
        required: true
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/users/{userId}/activation"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.userId: "method.request.path.userId"
        passthroughBehavior: "when_no_match"

  /reports/generate/{employeeId}/dot-mirror:
    post:
      tags:
        - Relatórios
      summary: Gerar relatório espelho de ponto
      description: Gera o relatório espelho de ponto de um funcionário
      operationId: generateDotMirrorReport
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/reports/generate/{employeeId}/dot-mirror"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
        passthroughBehavior: "when_no_match"

  /reports/generate/{employeeId}/dot-mirror/{year}/{month}:
    post:
      tags:
        - Relatórios
      summary: Gerar relatório espelho de ponto para um mês e ano especifico
      description: 'Gera o relatório espelho de ponto de um mês e ano especifico de um funcionário '
      operationId: generateDotMirrorReport_1
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: month
          in: path
          required: true
          schema:
            type: integer
            format: int32
        - name: year
          in: path
          required: true
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/reports/generate/{employeeId}/dot-mirror/{year}/{month}"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
          integration.request.path.month: "method.request.path.month"
          integration.request.path.year: "method.request.path.year"
        passthroughBehavior: "when_no_match"

  /point-records/employees/{employeeId}/record-point/{type}:
    post:
      tags:
        - Registro de Ponto
      summary: Registrar ponto
      description: Registra o ponto do funcionário
      operationId: recordPoint
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: type
          in: path
          required: true
          schema:
            type: string
            enum:
              - IN
              - OUT
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointRecordResponse'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/point-records/employees/{employeeId}/record-point/{type}"
        responses:
          default:
            statusCode: "200"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
          integration.request.path.type: "method.request.path.type"
        passthroughBehavior: "when_no_match"

  /point-records/manual-record-point:
    post:
      tags:
        - Registro de Ponto
      summary: Registrar ponto manual
      description: Registra o ponto do funcionário manualmente
      operationId: manualRecordPoint
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PointRecordRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointRecordResponse'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/point-records/manual-record-point"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  /login:
    post:
      tags:
        - autentication-controller
      operationId: login
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DadosAutenticacao'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Empty"
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/login"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  /employees:
    post:
      tags:
        - employee-controller
      summary: Criar funcionário
      description: Cria um funcionário
      operationId: create_1
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EmployeeRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
      x-amazon-apigateway-integration:
        httpMethod: "POST"
        uri: "${url_timesheet_service}/employees"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  /users/{userId}:
    get:
      tags:
        - Usuários
      summary: Consultar usuário
      description: Retorna um usuário
      operationId: findById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "${url_timesheet_service}/users/{userId}"
        requestParameters:
          integration.request.path.userId: "method.request.path.userId"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

    delete:
      tags:
        - Usuários
      summary: Deletar usuário
      description: Deleta um usuário
      operationId: delete
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: "DELETE"
        uri: "${url_timesheet_service}/users/{userId}"
        requestParameters:
          integration.request.path.userId: "method.request.path.userId"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  /point-records:
    get:
      tags:
        - Registro de Ponto
      summary: Listar pontos
      description: Retorna todos pontos
      operationId: list
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointRecordTotalResponse'
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "${url_timesheet_service}/point-records"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  /point-records/{pointRecordId}:
    get:
      tags:
        - Registro de Ponto
      summary: Consultar ponto
      description: Retorna um ponto
      operationId: findById_1
      parameters:
        - name: pointRecordId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointRecordResponse'
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "${url_timesheet_service}/point-records/{pointRecordId}"
        requestParameters:
          integration.request.path.pointRecordId: "method.request.path.pointRecordId"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  /point-records/list/{employeeId}:
    get:
      tags:
        - Registro de Ponto
      summary: Listar pontos
      description: Retorna todos pontos de um funcionário
      operationId: listByEmployeeId
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointRecordTotalResponse'
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "${url_timesheet_service}/point-records/list/{employeeId}"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  #/point-records/list-by-date/{employeeId}/{date}:
  /point-records/list-by-date/employees/{employeeId}/{date}:
    get:
      tags:
        - Registro de Ponto
      summary: Listar pontos por data
      description: Retorna todos pontos de um funcionário por data
      operationId: listByDateAndEmployeeId
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointRecordTotalResponse'
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "${url_timesheet_service}/point-records/list-by-date/employees/{employeeId}/{date}"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
          integration.request.path.date: "method.request.path.date"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  /point-records/list-by-date/{date}:
    get:
      tags:
        - Registro de Ponto
      summary: Listar pontos por data
      description: Retorna todos pontos por data
      operationId: listByDate
      parameters:
        - name: date
          in: path
          required: true
          schema:
            type: string
            format: date
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PointRecordTotalResponse'
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "${url_timesheet_service}/point-records/list-by-date/{date}"
        requestParameters:
          integration.request.path.date: "method.request.path.date"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

  /employees/{employeeId}:
    get:
      tags:
        - employee-controller
      summary: Consultar funcionário
      description: Consulta um funcionário
      operationId: findById_2
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EmployeeResponse'
      x-amazon-apigateway-integration:
        httpMethod: "GET"
        uri: "${url_timesheet_service}/employees/{employeeId}"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

    delete:
      tags:
        - employee-controller
      summary: Deletar funcionário
      description: Deleta um funcionário
      operationId: delete_1
      parameters:
        - name: employeeId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
      x-amazon-apigateway-integration:
        httpMethod: "DELETE"
        uri: "${url_timesheet_service}/employees/{employeeId}"
        requestParameters:
          integration.request.path.employeeId: "method.request.path.employeeId"
        responses:
          default:
            statusCode: "200"
        passthroughBehavior: "when_no_match"

components:
  schemas:
    PasswordUpdRequest:
      required:
        - password
      type: object
      properties:
        password:
          type: string
    UserResponse:
      type: object
      properties:
        userId:
          type: string
        employeeId:
          type: integer
          format: int64
        active:
          type: boolean
    UserRequest:
      required:
        - employeeId
        - password
        - userId
      type: object
      properties:
        userId:
          type: string
        password:
          type: string
        employeeId:
          type: integer
          format: int64
    UserActivationRequest:
      required:
        - active
      type: object
      properties:
        active:
          type: boolean
    LocalTime:
      type: object
      properties:
        hour:
          type: integer
          format: int32
        minute:
          type: integer
          format: int32
        second:
          type: integer
          format: int32
        nano:
          type: integer
          format: int32
    PointRecordResponse:
      type: object
      properties:
        pointRecordId:
          type: integer
          format: int64
        employeeId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        time:
          $ref: '#/components/schemas/LocalTime'
        type:
          type: string
          enum:
            - IN
            - OUT
    PointRecordRequest:
      type: object
      properties:
        pointRecordId:
          type: integer
          format: int64
        employeeId:
          type: integer
          format: int64
        date:
          type: string
          format: date
        time:
          $ref: '#/components/schemas/LocalTime'
        type:
          type: string
          enum:
            - IN
            - OUT
    DadosAutenticacao:
      type: object
      properties:
        login:
          type: string
        senha:
          type: string
    EmployeeRequest:
      required:
        - email
        - name
        - role
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - SELLER
            - BUYER
            - TECHNICIAN
    EmployeeResponse:
      type: object
      properties:
        employeeId:
          type: integer
          format: int64
        name:
          type: string
        email:
          type: string
        role:
          type: string
          enum:
            - SELLER
            - BUYER
            - TECHNICIAN
        active:
          type: boolean
    PointRecordTotalResponse:
      type: object
      properties:
        pointRecordResponseList:
          type: array
          items:
            $ref: '#/components/schemas/PointRecordResponse'
        totalWorkedHours:
          $ref: '#/components/schemas/LocalTime'
    Empty:
      title: "Empty Schema"
      type: "object"
