openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://load-balancer-pagamento-693861571.us-east-1.elb.amazonaws.com
    description: Generated server url
tags:
  - name: Pagamentos
    description: Controller que gerencia as ações possíveis do pagamento de um pedido
  - name: Pagamento Externo
    description: Controller que gerencia as ações possíveis de integracao com pagamento externo
  - name: Status de Pagamento
    description: Controller que gerencia os status de pagemento de um produto
  - name: Gerar Pagamento
    description: Controller que gerar o pagamento de um pedido
  - name: Forma de Pagamento
    description: Controller que gerencia as possíveis formas de pagamento de um pedido
paths:
  /pagamentos/{pagamentoId}/alterar-forma-pagamento:
    put:
      tags:
        - Pagamentos
      summary: Alterar forma de pagamento
      description: Altera a forma de pagamento de um pedido.
      operationId: cancelarPagamento
      parameters:
        - name: pagamentoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: formaPagamentoId
          in: query
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /pagamentos/{pedidoId}/reprocessar-pagamento:
    post:
      tags:
        - Pagamentos
      summary: Reprocessar pagamento
      description: Reprocessa o pagamento de um pedido.
      operationId: reprocessarPagamento
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /pagamentos/{pedidoId}/realizar-pagamento:
    post:
      tags:
        - Pagamentos
      summary: Realizar pagamento
      description: Realiza o pagamento de um pedido.
      operationId: realizarPagamento
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /pagamentos/{pedidoId}/cancelar-pagamento:
    post:
      tags:
        - Pagamentos
      summary: Cancelar pagamento
      description: Cancela o pagamento de um pedido.
      operationId: cancelarPagamento_1
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /pagamento-externo/mercadopago/{idPagamentoExterno}/cancelar:
    post:
      tags:
        - Pagamento Externo
      summary: Cancelar pagamento do Mercado Pago
      description: Cancela um pagamento que a forma de pagamento é Mercado Pago
      operationId: cancelarPagamento_2
      parameters:
        - name: idPagamentoExterno
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /pagamento-externo/mercadopago-webhook:
    post:
      tags:
        - Pagamento Externo
      summary: Webhook Pagamento
      description: Webhook para retorno de pagamento
      operationId: webhookPagamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PagamentoWebhookRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /pagamento-externo/mercadopago-webhook-simulacao:
    post:
      tags:
        - Pagamento Externo
      summary: Webhook para simular retorno pagamento externo
      description: Webhook para simular retorno de pagamento externo
      operationId: webhookPagamentoSimulacao
      parameters:
        - name: idPagamentoExterno
          in: query
          required: true
          schema:
            type: integer
            format: int64
        - name: statusMercadoPago
          in: query
          required: true
          schema:
            type: string
            enum:
              - APPROVED
              - REJECTED
              - CANCELLED
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /gerar-pagamento/pedido/{idPedido}/forma-pagamento/{formaPagamentoId}:
    post:
      tags:
        - Gerar Pagamento
      summary: Gerar pagamento de pedido
      description: Gera o pagamento de um pedido.
      operationId: gerarPagamento
      parameters:
        - name: idPedido
          in: path
          required: true
          schema:
            type: integer
            format: int64
        - name: formaPagamentoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /forma-pagamento:
    get:
      tags:
        - Forma de Pagamento
      summary: Listar forma de pagamento
      description: Retorna todas as formas de pagamento.
      operationId: listarFormaPagamentos
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/FormaPagamentoResponse'
    post:
      tags:
        - Forma de Pagamento
      summary: Criar forma de pagamento
      description: Cria uma nova forma de pagamento de um pedido.
      operationId: criarFormaPagamento
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormaPagamentoRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FormaPagamentoResponse'
  /forma-pagamento/{id}:
    get:
      tags:
        - Forma de Pagamento
      summary: Consultar forma de pagamento por ID
      description: Retorna a forma de pagamento de pedido.
      operationId: consultarFormaPagamento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FormaPagamentoResponse'
    delete:
      tags:
        - Forma de Pagamento
      summary: Deletar forma de pagamento
      description: Deleta um meio de pagamento de pedidos.
      operationId: deletarFormaPagamento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
    patch:
      tags:
        - Forma de Pagamento
      summary: Atualizar forma de pagamento
      description: Atualiza a forma de pagamento de um pedido.
      operationId: atualizarFormaPagamento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/FormaPagamentoRequest'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FormaPagamentoResponse'
  /status-pagamentos:
    get:
      tags:
        - Status de Pagamento
      summary: Listar status pagamento
      description: Retorna o status pagamento.
      operationId: listarStatusPedidos
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/StatusPagamentoResponse'
  /status-pagamentos/{id}:
    get:
      tags:
        - Status de Pagamento
      summary: Consultar status pagamento por ID
      description: Retorna o status pagamento.
      operationId: consultarStatusPagamento
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StatusPagamentoResponse'
  /status-pagamentos/consultar-por-nome/{nome}:
    get:
      tags:
        - Status de Pagamento
      summary: Consultar forma de pagamento por nome
      description: Retorna o status pagamento por nome.
      operationId: consultarStatusPagamentoPorNome
      parameters:
        - name: nome
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/StatusPagamentoResponse'
  /pagamentos:
    get:
      tags:
        - Pagamentos
      summary: Listar pagamentos
      description: Retorna todos pagamentos de pedidos.
      operationId: listarPagamentos
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PagamentoResponse'
  /pagamentos/{pedidoId}/consultar-pagamento-por-id-pedido:
    get:
      tags:
        - Pagamentos
      summary: consultar pagamento por id pedido
      description: Retorna o pagamento por id pedido
      operationId: consultarPagamentoPorIdPedido
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /pagamentos/{pagamentoId}:
    get:
      tags:
        - Pagamentos
      summary: Consultar pagamento
      description: Retorna o pagamento do pedido.
      operationId: consultarPagamento
      parameters:
        - name: pagamentoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /pagamentos/{pagamentoExternoId}/consultar-por-id-pagamento-externo:
    get:
      tags:
        - Pagamentos
      summary: Consultar pagamento por id pagamento externo
      description: Retorna o pagamento por id pagamento externo.
      operationId: consultarPorIdPagamentoExterno
      parameters:
        - name: pagamentoExternoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/PagamentoResponse'
  /forma-pagamento/consultar-por-nome/{nome}:
    get:
      tags:
        - Forma de Pagamento
      summary: Consultar forma de pagamento por nome
      description: Retorna a forma de pagamento de pedido por nome.
      operationId: consultarFormaPagamentoPorNome
      parameters:
        - name: nome
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/FormaPagamentoResponse'
components:
  schemas:
    FormaPagamentoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        externo:
          type: boolean
        ativo:
          type: boolean
    PagamentoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        valor:
          type: number
          format: double
        formaPagamento:
          $ref: '#/components/schemas/FormaPagamentoResponse'
        statusPagamento:
          $ref: '#/components/schemas/StatusPagamentoResponse'
        pedidoId:
          type: integer
          format: int64
        idPagamentoExterno:
          type: integer
          format: int64
        qrCode:
          type: string
        urlPagamento:
          type: string
        dataHoraCriado:
          type: string
          format: date-time
        dataHoraFinalizado:
          type: string
          format: date-time
    StatusPagamentoResponse:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        ativo:
          type: boolean
    PagamentoWebhookDataRequest:
      required:
        - id
      type: object
      properties:
        id:
          type: string
    PagamentoWebhookRequest:
      type: object
      properties:
        id:
          type: string
        live_mode:
          type: boolean
        type:
          type: string
        date_created:
          type: string
        user_id:
          type: integer
          format: int64
        api_version:
          type: string
        action:
          type: string
        data:
          $ref: '#/components/schemas/PagamentoWebhookDataRequest'
    FormaPagamentoRequest:
      required:
        - nome
      type: object
      properties:
        nome:
          type: string
        externo:
          type: boolean
        ativo:
          type: boolean
