openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://load-balancer-cozinha-1458632615.us-east-1.elb.amazonaws.com
    description: Generated server url
tags:
  - name: Produção Pedido
    description: Controller que gerencia a produção dos pedidos na cozinha
  - name: Cozinha Pedido
    description: Controller que gerencia os pedidos na cozinha
paths:
  /producao-pedido/{pedidoId}/receber-pedido:
    post:
      tags:
        - Produção Pedido
      summary: Receber pedido
      description: Receber o pedido.
      operationId: receberPedido
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /producao-pedido/{pedidoId}/retirar:
    patch:
      tags:
        - Produção Pedido
      summary: Entregar pedido
      description: Realiza a entrega do pedido.
      operationId: retirarPedido
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CozinhaPedidoResponse'
  /producao-pedido/{pedidoId}/iniciar-preparo:
    patch:
      tags:
        - Produção Pedido
      summary: Iniciar preparo
      description: Inicia o preparo de um pedido.
      operationId: iniciarPreparo
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CozinhaPedidoResponse'
  /producao-pedido/{pedidoId}/finalizar-preparo:
    patch:
      tags:
        - Produção Pedido
      summary: Finalizar preparo
      description: Finaliza o preparo de pedido.
      operationId: finalizarPreparo
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CozinhaPedidoResponse'
  /cozinha-pedido/{cozinhaId}:
    get:
      tags:
        - Cozinha Pedido
      operationId: consultarPorIdPedido
      parameters:
        - name: cozinhaId
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CozinhaPedidoResponse'
  /cozinha-pedido/pedido/{pedidoId}:
    get:
      tags:
        - Cozinha Pedido
      operationId: consultarPorIdPedido_1
      parameters:
        - name: pedidoId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/CozinhaPedidoResponse'
  /cozinha-pedido/listar:
    get:
      tags:
        - Cozinha Pedido
      operationId: listar
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/CozinhaPedidoResponse'
components:
  schemas:
    CozinhaPedidoResponse:
      type: object
      properties:
        cozinhaId:
          type: string
        dataRecebimentoDoPedido:
          type: string
          format: date-time
        dataInicioPreparo:
          type: string
          format: date-time
        dataFinalizacaoPreparo:
          type: string
          format: date-time
        dataEntregaPedido:
          type: string
          format: date-time
        idPedido:
          type: integer
          format: int64
        statusPedido:
          type: string
        processoAtual:
          type: string
